export const FETCH_CRYPTO_CURRENCIES_REQUEST = 'FETCH_CRYPTO_CURRENCIES_REQUEST';
export const FETCH_CRYPTO_CURRENCIES_SUCCESS = 'FETCH_CRYPTO_CURRENCIES_SUCCESS';
export const FETCH_CRYPTO_CURRENCIES_FAILURE = 'FETCH_CRYPTO_CURRENCIES_FAILURE';
